#!/bin/bash
#
# from: https://stackoverflow.com/questions/54578066/how-to-build-a-docker-image-on-a-specific-architecture-with-docker-hub

docker run --rm --privileged multiarch/qemu-user-static:register --reset